name: Build Triton Inference Server

on:
  push:
    branches: [ main ]

jobs:
  build-gpu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build GPU Image
        run: python3 build.py --image gpu-base,nvcr.io/nvidia/tritonserver:22.04-py3-min --backend ensemble:main --backend pytorch:main --backend python:main --no-container-interactive
      - name: Save GPU Image
        run: |
          IMAGE_ID=$(docker images | grep -v "cibase" | awk '{print $3}')
          docker tag $IMAGE_ID seyedehsanhosseini/tritonserver/tritonserver:gpu
          docker push seyedehsanhosseini/tritonserver/tritonserver:gpu
          echo "::set-output name=cpu-image::seyedehsanhosseini/tritonserver/tritonserver:gpu"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  build-cpu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build CPU Image
        run: python3 build.py --image base,nvcr.io/nvidia/tritonserver:22.04-py3-min --enable-gpu --backend ensemble:main --backend pytorch:main --backend python:main --no-container-interactive
      - name: Save CPU Image
        run: |
          IMAGE_ID=$(docker images | grep -v "cibase" | awk '{print $3}')
          docker tag $IMAGE_ID seyedehsanhosseini/tritonserver/tritonserver:cpu
          docker push seyedehsanhosseini/tritonserver/tritonserver:cpu
          echo "::set-output name=cpu-image::seyedehsanhosseini/tritonserver/tritonserver:cpu"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  create-release:
    needs: [build-gpu, build-cpu]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            This is an automated release created by the GitHub Actions workflow.
          draft: false
          prerelease: false
      - name: Upload GPU Image
        uses: actions/upload-artifact@v2
        with:
          name: TritonServer GPU Image
          path: <path to gpu image file>
          if: steps.build-gpu.outputs.gpu-image != ''
      - name: Upload CPU Image
        uses: actions/upload-artifact@v2
        with:
          name: TritonServer CPU Image
          path: <path to cpu image file>
          if: steps.build-cpu.outputs.cpu-image != ''
